@extends('layouts.main1')



@section('content')
<style>
    p{
        color: #5b6c8f;
    font-size: 16px;
    line-height: 20px;
    }
    li{
      color: #5b6c8f;
    font-size: 16px;
    /* line-height: 26px */
    margin-bottom:6px;
    }

    .list li{
        list-style: none;
    }
    .ps-privacy__title{
  font-size: 50px;
  line-height: 60px;
  font-size: 34px;
  line-height: 40px;
  margin-bottom: 20px;
  text-align: center;
  color: #103178;
}
</style>
<div>
    <div class="container">
       <ul class="ps-breadcrumb">
            <li class="ps-breadcrumb__item"><a href="{{route('home')}}">Home</a></li>
            <li class="ps-breadcrumb__item active" aria-current="page">TREMS AND CONDITION</li>
        </ul>
        <div>
            <div class="row">
                <div class="col-md-12">
                    <h2 class="ps-privacy__title">TERMS AND CONDITION</h2>
                    <p style="color: #103178;"><b>PLEASE READ THESE TERMS OF USE CAREFULLY. BY ACCESSING OR USING THE WEBSITE, YOU AGREE TO BE BOUND BY THE TERMS DESCRIBED HEREIN AND ALL TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE WEBSITE.</b></p>
                    <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. <br> <br>
                       This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.Indiherbo.com website. <br> <br>
                       The domain name www.Indiherbo.com (hereinafter referred to as 'Website') is owned by Indiherbo, a company incorporated under the provisions of the Indian Partnership Act, 1932 with its registered office at X-35, Okhla Industrial Area, Phase-II, New Delhi -110020 (hereinafter referred to as 'Indiherbo'). <br> <br>
                       Your use of the Website and services and tools are governed by the following terms and conditions ('Terms of Use') as applicable to the Website including the applicable policies which are incorporated herein by way of reference. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. By mere use of the Website, You shall be contracting with Indiherbo and these terms and conditions including the policies constitute your binding obligations with Indiherbo. <br> <br>
                       For the purpose of these Terms of Use, the terms "we", "us" and "our" refer to Indiherbo. Indiherbo offers this website, including all information, tools and services available from this site to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated here. <br> <br>
                       By visiting our site and/ or purchasing something from us, you engage in our "Service" and agree to be bound by the following terms and conditions ("Terms of Service", "Terms"), including those additional terms and conditions and policies referenced herein and/or available by hyperlink. These Terms of Service apply to all users of the site, including without limitation users who are browsers, vendors, customers, merchants, and/ or contributors of content. <br> <br>
                       When you use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to you. It is your responsibility to review these Terms of Use periodically for updates/changes. Your continued use of the Website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website. <br> <br>
                       ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Indiherbo Policies (including but not limited to Privacy Policy available at Privacy) as amended from time to time. <br> <br>
                       These Terms of Use is published in compliance of, and is governed by the provisions of Indian laws, including but limited to: <br> <br>
                    </p>
                    <ul>
                        <li>the Indian Contract Act, 1872 ("Contract Act");</li>
                        <li>the (Indian) Information Technology Act, 2000 ("IT Act") and the rules, regulations, guidelines and clarifications framed thereunder, including the (Indian) Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011, and the (Indian) Information Technology (Intermediaries Guidelines) Rules, 2011 ("IG Guidelines");</li>
                        <li>the Drugs and Cosmetic Act, 1940 ("Drugs Act"), read with the Drugs and Cosmetics Rules, 1945 ("Drugs Rules");</li>
                        <li>the Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954 ("Drugs and Magic Act");</li>
                        <li>The Indian Medical Council Act, 1956 read with the Indian Medical Council Rules, 1957;</li>
                        <li>Pharmacy Act, 1948 ("Pharmacy Act") and</li>
                        <li>The Consumer Protection Act, 1986.</li>
                    </ul>
                    <p style="color: #103178;"><b>Use of the Website</b></p>
                    <p>You agree, undertake and confirm that your use of Website shall be strictly governed by the following binding principles: <br>
                       You shall not host, display, upload, modify, publish, transmit, update or share any information which: <br>
                    </p>
                    <ul class="list"> 
                        <li>1.	belongs to another person and to which You does not have any right to;</li>
                        <li>2.	Is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to 'indecent representation of women' within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</li>
                        <li>3.	is misleading in any way;</li>
                        <li>4.	is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;</li>
                        <li>5.	harasses or advocates harassment of another person;</li>
                        <li>6.	involves the transmission of 'junk mail', 'chain letters', or unsolicited mass mailing or 'spamming';</li>
                        <li>7.	promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;</li>
                        <li>8.	infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];</li>
                        <li>9.	promotes an illegal or unauthorized copy of another person's copyrighted work (see 'Copyright complaint' below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;</li>
                        <li>10.	contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</li>
                        <li>11.	provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</li>
                        <li>12.	provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</li>
                        <li>13.	contains video, photographs, or images of another person (with a minor or an adult).</li>
                        <li>14.	tries to gain unauthorized access or exceeds the scope of authorized access to the Website or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Website or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</li>
                        <li>15.	engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of 'virtual' products related to the Website. Throughout this Terms of Use, Indiherbo's prior written consent means a communication coming from Indiherbo's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;</li>
                        <li>16.	solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;</li>
                        <li>17.	interferes with another USER's use and enjoyment of the Website or any other individual's User and enjoyment of similar services;</li>
                        <li>18.	refers to any website or URL that, in Our sole discretion, contains material that is inappropriate for the Website or any other website, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</li>
                        <li>19.	harm minors in any way;</li>
                        <li>20.	infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;</li>
                        <li>21.	violates any law for the time being in force;</li>
                        <li>22.	deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                        <li>23.	impersonate another person;</li>
                        <li>24.	contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancel bots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</li>
                        <li>25.	threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li>
                        <li>26.	shall not be false, inaccurate or misleading;</li>
                        <li>27.	shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.</li>
                        <li>28.	shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ('ISPs') or other suppliers;</li>
                    </ul>
                    <p>
                    You shall not use any 'deep-link', 'page-scrape', 'robot', 'spider' or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve our right to bar any such activity. <br> <br>
                    You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password 'mining' or any other illegitimate means. <br> <br>
                    </p>
                    <p style="color: #103178;"><b>Membership Eligibility</b></p>
                    <p>Use of the Website is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are 'incompetent to contract' within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use the Website. If you are a minor i.e. under the age of 18 years, you shall not register as a User of the website and shall not transact on or use the website. As a minor if you wish to use or transact on website, such use or transaction may be made by your legal guardian or parents on the Website. Indiherbo reserves the right to terminate your membership and / or refuse to provide you with access to the Website if it is brought to Indiherbo's notice or if it is discovered that you are under the age of 18 years.</p>
                    <p style="color: #103178;"><b>Your Account and Registration Obligations</b></p>
                    <p>If you use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and you shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.</p>
                    <p style="color: #103178;"><b>Communications</b></p>
                    <p>When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.</p>
                    <p style="color: #103178;"><b>Platform for Transaction and Communication</b></p>
                    <p>The Website is a platform that Users utilize to meet and interact with one another for their transactions. Indiherbo is not and cannot be a party to or control in any manner any transaction between the Website's Users.</p>
                    <p style="color: #103178;"><b>General Conditions</b></p>
                    <p>We reserve the right to refuse service to anyone for any reason at any time. <br> <br>
                       You understand that your content (not including credit card information), may be transferred unencrypted and involve (a) transmissions over various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices. Credit card information is always encrypted during transfer over networks. <br> <br>
                       You agree not to reproduce, duplicate, copy, sell, resell or exploit any portion of the Service, use of the Service, or access to the Service or any contact on the website through which the service is provided, without express written permission by us. <br> <br>
                       The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms. <br> <br>
                    </p>
                    <p style="color: #103178;"><b>Accuracy, Completeness and Timeliness of Information</b></p>
                    <p>We are not responsible if information made available on this site is not accurate, complete or current. The material on this site is provided for general information only and should not be relied upon or used as the sole basis for making decisions without consulting primary, more accurate, more complete or more timely sources of information. Any reliance on the material on this site is at your own risk. <br> <br>
                       This site may contain certain historical information. Historical information, necessarily, is not current and is provided for your reference only. We reserve the right to modify the contents of this site at any time, but we have no obligation to update any information on our site. You agree that it is your responsibility to monitor changes to our site. <br>
                    </p>
                    <p style="color: #103178;"><b>Modifications to the Service and Prices</b></p>
                    <p>Prices for our products are subject to change without notice. <br>
                       We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time. <br>
                       We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service. <br>
                    </p>
                    <p style="color: #103178;"><b>Products or Services</b></p>
                    <p>Certain products or services may be available exclusively online through the website. These products or services may have limited quantities and are subject to return or exchange only according to our Return Policy. <br> <br>
                       We have made every effort to display as accurately as possible the colors and images of our products that appear at the store. We cannot guarantee that your computer monitor's display of any color will be accurate. <br> <br>
                       We reserve the right, but are not obligated, to limit the sales of our products or Services to any person, geographic region or jurisdiction. We may exercise this right on a case-by-case basis. We reserve the right to limit the quantities of any products or services that we offer. All descriptions of products or product pricing are subject to change at anytime without notice, at the sole discretion of us. We reserve the right to discontinue any product at any time. Any offer for any product or service made on this site is void where prohibited. <br> <br>
                       We do not warrant that the quality of any products, services, information, or other material purchased or obtained by you will meet your expectations, or that any errors in the Service will be corrected. <br> <br>
                    </p>
                    <p style="color: #103178;"><b>Accuracy of Billing and Account Information</b></p>
                    <p>We reserve the right to refuse any order you place with us. We may, in our sole discretion, limit or cancel quantities purchased per person, per household or per order. These restrictions may include orders placed by or under the same customer account, the same credit card, and/or orders that use the same billing and/or shipping address. In the event that we make a change to or cancel an order, we may attempt to notify you by contacting the e-mail and/or billing address/phone number provided at the time the order was made. We reserve the right to limit or prohibit orders that, in our sole judgment, appear to be placed by dealers, resellers or distributors. <br> <br>
                       You agree to provide current, complete and accurate purchase and account information for all purchases made at our store. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed. <br> <br>
                       For more detail, please review our Returns Policy. <br> <br>
                    </p>
                    <p style="color: #103178;"><b>Optional Tools</b></p>
                    <p>We may provide you with access to third-party tools over which we neither monitor nor have any control nor input. <br>                           <br>
                       You acknowledge and agree that we provide access to such tools "as is" and "as available" without any warranties, representations or conditions of any kind and without any endorsement. We shall have no liability whatsoever arising from or relating to your use of optional third-party tools. <br> <br>                          
                       Any use by you of optional tools offered through the site is entirely at your own risk and discretion and you should ensure that you are familiar with and approve of the terms on which tools are provided by the relevant third-party provider(s). <br>   <br>                        
                       We may also, in the future, offer new services and/or features through the website (including, the release of new tools and resources). Such new features and/or services shall also be subject to these Terms of Service. <br> <br>                          
                    </p>
                    <p style="color: #103178;"><b>Third-Party Links</b></p>
                    <p>Certain content, products and services available via our Service may include materials from third-parties. <br>
                       We are not liable for any harm or damages related to the purchase or use of goods, services, resources, content, or any other transactions made in connection with any third-party websites. Please review carefully the third-party's policies and practices and make sure you understand them before you engage in any transaction. Complaints, claims, concerns, or questions regarding third-party products should be directed to the third-party. <br>
                   </p>
                    <p style="color: #103178;"><b>User Comments, Feedback and Other Submissions</b></p>
                    <p>If, at our request, you send certain specific submissions (for example contest entries) or without a request from us you send creative ideas, suggestions, proposals, plans, or other materials, whether online, by email, by postal mail, or otherwise (collectively, 'comments'), you agree that we may, at any time, without restriction, edit, copy, publish, distribute, translate and otherwise use in any medium any comments that you forward to us. We are and shall be under no obligation (1) to maintain any comments in confidence; (2) to pay compensation for any comments; or (3) to respond to any comments. <br> <br>
                       We may, but have no obligation to, monitor, edit or remove content that we determine in our sole discretion are unlawful, offensive, threatening, libelous, defamatory, pornographic, obscene or otherwise objectionable or violates any party"s intellectual property or these Terms of Service. <br> <br>
                       You agree that your comments will not violate any right of any third-party, including copyright, trademark, privacy, personality or other personal or proprietary right. You further agree that your comments will not contain libelous or otherwise unlawful, abusive or obscene material, or contain any computer virus or other malware that could in any way affect the operation of the Service or any related website. You may not use a false e-mail address, pretend to be someone other than yourself, or otherwise mislead us or third-parties as to the origin of any comments. You are solely responsible for any comments you make and their accuracy. We take no responsibility and assume no liability for any comments posted by you or any third-party. <br> <br>
                    </p>
                    <p style="color: #103178;"><b>Personal Information</b></p>
                    <p>Your submission of personal information through the store is governed by our Privacy Policy.</p>
                    <p style="color: #103178;"><b>Errors, Inaccuracies and Omissions</b></p>
                    <p>Occasionally there may be information on our site or in the Service that contains typographical errors, inaccuracies or omissions that may relate to product descriptions, pricing, promotions, offers, product shipping charges, transit times and availability. We reserve the right to correct any errors, inaccuracies or omissions, and to change or update information or cancel orders if any information in the Service or on any related website is inaccurate at any time without prior notice (including after you have submitted your order). <br>
                       We undertake no obligation to update, amend or clarify information in the Service or on any related website, including without limitation, pricing information, except as required by law. No specified update or refresh date applied in the Service or on any related website, should be taken to indicate that all information in the Service or on any related website has been modified or updated. <br>
                    </p>
                    <p style="color: #103178;"><b>Prohibited Uses</b></p>
                    <p>In addition to other prohibitions as set forth in the Terms of Service, you are prohibited from using the site or its content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
                    <p style="color: #103178;"><b>Disclaimer of Warranties; Limitation of Liability</b></p>
                    <p>We do not guarantee, represent or warrant that your use of our service will be uninterrupted, timely, secure or error-free. <br> <br>
                       We do not warrant that the results that may be obtained from the use of the service will be accurate or reliable. <br> <br>
                       You agree that from time to time we may remove the service for indefinite periods of time or cancel the service at any time, without notice to you. <br> <br>
                       You expressly agree that your use of, or inability to use, the service is at your sole risk. The service and all products and services delivered to you through the service are (except as expressly stated by us) provided 'as is' and 'as available' for your use, without any representation, warranties or conditions of any kind, either express or implied, including all implied warranties or conditions of merchantability, merchantable quality, fitness for a particular purpose, durability, title, and non-infringement. <br> <br>
                       In no case shall Indiherbo, our directors, officers, employees, affiliates, agents, contractors, interns, suppliers, service providers or licensors be liable for any injury, loss, claim, or any direct, indirect, incidental, punitive, special, or consequential damages of any kind, including, without limitation lost profits, lost revenue, lost savings, loss of data, replacement costs, or any similar damages, whether based in contract, tort (including negligence), strict liability or otherwise, arising from your use of any of the service or any products procured using the service, or for any other claim related in any way to your use of the service or any product, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of the service or any content (or product) posted, transmitted, or otherwise made available via the service, even if advised of their possibility. Because some states or jurisdictions do not allow the exclusion or the limitation of liability for consequential or incidental damages, in such states or jurisdictions, our liability shall be limited to the maximum extent permitted by law. <br> <br>
                    </p>
                    <p style="color: #103178;"> <b>Indemnification</b></p>
                    <p>You agree to indemnify, defend and hold harmless Indiherbo and our parent, subsidiaries, affiliates, partners, officers, directors, agents, contractors, licensors, service providers, subcontractors, suppliers, interns and employees, harmless from any claim or demand, including reasonable attorneys" fees, made by any third-party due to or arising out of your breach of these Terms of Service or the documents they incorporate by reference, or your violation of any law or the rights of a third-party.</p>
                    <p style="color: #103178;"><b>Severability</b></p>
                    <p>In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service, such determination shall not affect the validity and enforceability of any other remaining provisions.</p>
                    <p style="color: #103178;"><b>Termination</b></p>
                    <p>The obligations and liabilities of the parties incurred prior to the termination date shall survive the termination of this agreement for all purposes. <br>
                       These Terms of Service are effective unless and until terminated by either you or us. You may terminate these Terms of Service at any time by notifying us that you no longer wish to use our Services, or when you cease using our site. <br>
                       If in our sole judgment you fail, or we suspect that you have failed, to comply with any term or provision of these Terms of Service, we also may terminate this agreement at any time without notice and you will remain liable for all amounts due up to and including the date of termination; and/or accordingly may deny you access to our Services (or any part thereof). <br>
                    </p>
                       <p style="color: #103178;"><b>Entire Agreement</b></p>
                    <p>The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. <br>
                       These Terms of Service and any policies or operating rules posted by us on this site or in respect to The Service constitutes the entire agreement and understanding between you and us and govern your use of the Service, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of the Terms of Service). <br>
                       Any ambiguities in the interpretation of these Terms of Service shall not be construed against the drafting party. <br>
                    </p>
                       <p style="color: #103178;"><b>Governing Law</b></p>
                       <p>These Terms of Service and any separate agreements whereby we provide you Services shall be governed by and construed in accordance with the laws of India and jurisdiction of Delhi</p>
                       <p style="color: #103178;"><b>Changes to Terms of Service</b></p>
                       <p>You can review the most current version of the Terms of Service at any time at this page. <br>
                       We reserve the right, at our sole discretion, to update, change or replace any part of these Terms of Service by posting updates and changes to our website. It is your responsibility to check our website periodically for changes. Your continued use of or access to our website or the Service following the posting of any changes to these Terms of Service constitutes acceptance of those changes. <br>
                       </p>
                       <p style="color: #103178;"><b>Contact Information</b></p>
                       <p>Questions about the Terms of Service should be sent to us at customer-indiherbo@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection